let playlist = [" Pumped Up Kicks "," Leg Break ",[0,1,[2,3,4]], true ," Flagpole ", false, ];
document.write(playlist+"<br>");
document.write(playlist.length+"<br>");
document.write(playlist[playlist.length-1]+"<br>");
playlist.pop();
document.write(playlist+"<br>");
playlist.shift();
document.write(playlist+"<br>");
playlist.push("Hello");
document.write(playlist+"<br>");
playlist.unshift("World");
document.write(playlist+"<br>");
document.write(playlist[2][2][2]);
